### ISSUE TITLE
[Feature]: simple director basket provided

### ISSUE THREAD

**Issue by tomabg** [NETWAYS/check_checksum#4]
### Describe the feature request

i have created a simple director basket for this check command probably usefull for implementation

implementation is like this:
download checksum  file:

curl -o /usr/lib/nagios/plugins/check_checksum https://raw.githubusercontent.com/NETWAYS/check_checksum/master/check_checksum

make file executable:

chmod +x /usr/lib/nagios/plugins/check_checksum

import director basket for command defintion and service Template definitions(2 as i have seperated the interval)

Create Apply rule(s) like this in director

see here: [link](https://community.icinga.com/t/windows-agent-install-ps-plugins-and-service/13401/5)

director basket attached
[Director-Basket_checksum_basket_33b4bb4.json](https://github.com/NETWAYS/check_checksum/files/14880118/Director-Basket_checksum_basket_33b4bb4.json)

**Comment by martialblog** [comment]
Hi, thanks for the configuration. We could add it in a `contrib/` directory so that it is available for other users
